class Icons:
    BRAND = "◈"
    OVERVIEW = "◫"
    PLAYGROUND = "⚡"
    BENCHMARK = "⌁"
    PREDICTION = "◆"
    ANALYTICS = "◌"
    DEVELOPER = "</>"
    SETTINGS = "⚙"
    API = "●"
    SDK = "◇"
    ENGINE = "✦"
    CACHE = "↻"
